/**
 * Writes `src/theme-root.generated.css` from the default workspace theme.
 * Run from package `generate:theme-css` (also before `dev` / `build`).
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { getDocumentStaticThemeCss } from "../src/lib/theme/theme.ts";
import { defaultTheme } from "../src/lib/theme/themes/index.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, "../src/theme-root.generated.css");
const banner =
  "/* AUTO-GENERATED by scripts/generate-theme-root-css.ts — do not edit by hand */\n\n";
const css = `${banner}${getDocumentStaticThemeCss(defaultTheme)}\n`;
writeFileSync(outPath, css, "utf8");
console.log(`Wrote ${outPath}`);
